dependency packet: QT 4.2.1 and libiconv


build QT 4.2.1 and libiconv 1.11

environment:
* X (ex: linux) or mac osX

compile QT 4.2.1
get qt-x11-opensource-src-4.2.1.tar.gz
cd qt-x11-opensource-src-4.2.1
tar zxvf qt-x11-opensource-src-4.2.1.tar.gz
./configure
make
make install

compile libiconv 1.11
get libiconv-1.11.tar.gz
cd libiconv-1.11
tar libiconv-1.11.tar.gz
./configure
make
make install


environment:
* ms windows

from ftp.trolltech.com
get qt/source/qt-win-opensource-4.2.1-mingw.exe

from ftp.gnu.org
get gnu/lib/iconv/libiconv-1.9.1.bin.woe32.zip




compile this program
/usr/local/Trolltech/Qt-4.2.1/bin/qmake ftp.pro
make

and see a ftp executable file.
